modLoader="javafml"
loaderVersion="[36,)"
license="Unlicense"
[[mods]]
modId="sactweaker" 
version="${file.jarVersion}"
displayName="SACTweaker"
authors="Team Potato"
description='''
The shark is sooooooooooooo cute.
'''
[[dependencies.sactweaker]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sactweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
